/**
 * Authenticated encryption for invoice PDF attachments.
 *
 * Finance PDFs are stored in Sanity, and Sanity asset files are publicly
 * reachable regardless of dataset privacy ("Asset files are not private, so
 * even images uploaded to a private dataset can be viewed by unauthenticated
 * users" — Sanity docs). So the bytes that leave this process are ALWAYS
 * ciphertext. The plaintext PDF exists only in memory, server-side.
 *
 * Algorithm: AES-256-GCM (authenticated encryption, Node's built-in crypto —
 * no third-party dependency).
 *
 * ---------------------------------------------------------------------------
 * 2MGENC blob layout
 * ---------------------------------------------------------------------------
 *
 *   offset  0 : magic     "2MGENC"      6 bytes  (ASCII)
 *   offset  6 : version   0x01          1 byte
 *   offset  7 : IV                     12 bytes  (random per seal)
 *   offset 19 : auth tag               16 bytes  (GCM)
 *   offset 35 : ciphertext             remainder
 *
 *   header = 35 bytes. GCM is a stream mode, so
 *   ciphertext.length === plaintext.length exactly.
 *
 * Everything needed to decrypt except the key travels inside the blob, so a
 * stored asset can never be orphaned from its IV or tag.
 *
 * ---------------------------------------------------------------------------
 * AAD (additional authenticated data)
 * ---------------------------------------------------------------------------
 *
 *   AAD = utf8(invoiceId + "\0" + attachmentId)
 *
 * The AAD is authenticated but not encrypted. It binds the ciphertext to one
 * specific invoice AND one specific attachment, so a blob cannot be moved
 * between invoices: decryption with a different invoiceId or attachmentId
 * fails the GCM tag check and throws. `attachmentId` is generated by us BEFORE
 * encryption (the Sanity assetId does not exist until after upload, so it
 * cannot be part of the AAD).
 *
 * ---------------------------------------------------------------------------
 * Keys
 * ---------------------------------------------------------------------------
 *
 *   ATTACHMENT_ENC_KEY_V1        the 32-byte key for blob version 1
 *   ATTACHMENT_ENC_KEY_CURRENT   which version new blobs are sealed with ("1")
 *
 * Accepted key encodings (must decode to EXACTLY 32 bytes):
 *   - 64 hex characters, or
 *   - base64 / base64url (43 characters unpadded)
 *
 * Generate one with (never commit the output):
 *   node -e "console.log(require('crypto').randomBytes(32).toString('base64url'))"
 *
 * The version byte lets old blobs keep decrypting with their original key
 * after a rotation: add ATTACHMENT_ENC_KEY_V2, set ATTACHMENT_ENC_KEY_CURRENT=2,
 * and V1 blobs still open because they say so in their own header.
 *
 * LOSING A KEY IS UNRECOVERABLE. There is no backdoor: every attachment sealed
 * with that key becomes permanently unreadable.
 *
 * Every failure throws AttachmentCryptoError with a `code` — nothing here ever
 * degrades quietly or returns partial plaintext.
 */

const crypto = require("crypto");

const MAGIC = Buffer.from("2MGENC", "ascii"); // 6 bytes
const VERSION_OFFSET = MAGIC.length;          // 6
const IV_OFFSET = VERSION_OFFSET + 1;         // 7
const IV_LEN = 12;
const TAG_OFFSET = IV_OFFSET + IV_LEN;        // 19
const TAG_LEN = 16;
const HEADER_LEN = TAG_OFFSET + TAG_LEN;      // 35
const KEY_LEN = 32;
const SUPPORTED_VERSIONS = [1];

class AttachmentCryptoError extends Error {
  constructor(code, message) {
    super(message);
    this.name = "AttachmentCryptoError";
    this.code = code;
  }
}

/* --------------------------------- keys ---------------------------------- */

function decodeKey(raw, varName) {
  if (typeof raw !== "string" || raw.length === 0) {
    throw new AttachmentCryptoError("KEY_MISSING", varName + " is not set");
  }
  let buf;
  if (/^[0-9a-fA-F]{64}$/.test(raw)) {
    buf = Buffer.from(raw, "hex");
  } else {
    let s = raw.replace(/-/g, "+").replace(/_/g, "/");
    while (s.length % 4) s += "=";
    buf = Buffer.from(s, "base64");
  }
  if (buf.length !== KEY_LEN) {
    // Never echo the value itself — only its decoded length.
    throw new AttachmentCryptoError(
      "KEY_INVALID",
      varName + " must decode to exactly 32 bytes (got " + buf.length + ")"
    );
  }
  return buf;
}

function keyForVersion(version) {
  const varName = "ATTACHMENT_ENC_KEY_V" + version;
  return decodeKey(process.env[varName], varName);
}

function currentVersion() {
  const raw = process.env.ATTACHMENT_ENC_KEY_CURRENT;
  const v = parseInt(raw, 10);
  if (!Number.isInteger(v) || SUPPORTED_VERSIONS.indexOf(v) === -1) {
    throw new AttachmentCryptoError(
      "KEY_INVALID",
      "ATTACHMENT_ENC_KEY_CURRENT must be one of: " + SUPPORTED_VERSIONS.join(", ")
    );
  }
  return v;
}

/* ---------------------------------- AAD ---------------------------------- */

function buildAad(invoiceId, attachmentId) {
  if (typeof invoiceId !== "string" || invoiceId.length === 0) {
    throw new AttachmentCryptoError("BAD_AAD", "invoiceId is required");
  }
  if (typeof attachmentId !== "string" || attachmentId.length === 0) {
    throw new AttachmentCryptoError("BAD_AAD", "attachmentId is required");
  }
  return Buffer.from(invoiceId + "\0" + attachmentId, "utf8");
}

// Opaque, unguessable, and generated before encryption so it can go in the AAD.
function newAttachmentId() {
  return crypto.randomBytes(16).toString("hex"); // 32 chars
}

/* -------------------------------- sealing -------------------------------- */

function sealAttachment(opts) {
  opts = opts || {};
  const plaintext = opts.plaintext;
  if (!Buffer.isBuffer(plaintext)) {
    throw new AttachmentCryptoError("BAD_INPUT", "plaintext must be a Buffer");
  }
  if (plaintext.length === 0) {
    throw new AttachmentCryptoError("BAD_INPUT", "plaintext is empty");
  }

  const version = currentVersion();
  const key = keyForVersion(version);
  const aad = buildAad(opts.invoiceId, opts.attachmentId);
  const iv = crypto.randomBytes(IV_LEN);

  const cipher = crypto.createCipheriv("aes-256-gcm", key, iv, { authTagLength: TAG_LEN });
  cipher.setAAD(aad);
  const ciphertext = Buffer.concat([cipher.update(plaintext), cipher.final()]);
  const tag = cipher.getAuthTag();

  const header = Buffer.alloc(HEADER_LEN);
  MAGIC.copy(header, 0);
  header[VERSION_OFFSET] = version;
  iv.copy(header, IV_OFFSET);
  tag.copy(header, TAG_OFFSET);

  return Buffer.concat([header, ciphertext]);
}

/* ------------------------------- unsealing -------------------------------- */

function openAttachment(opts) {
  opts = opts || {};
  const blob = opts.blob;
  if (!Buffer.isBuffer(blob)) {
    throw new AttachmentCryptoError("BAD_INPUT", "blob must be a Buffer");
  }
  if (blob.length < HEADER_LEN) {
    throw new AttachmentCryptoError("TRUNCATED_BLOB", "blob is shorter than the 35-byte header");
  }
  if (!blob.subarray(0, MAGIC.length).equals(MAGIC)) {
    throw new AttachmentCryptoError("MAGIC_MISMATCH", "blob is not a 2MGENC attachment");
  }

  const version = blob[VERSION_OFFSET];
  if (SUPPORTED_VERSIONS.indexOf(version) === -1) {
    throw new AttachmentCryptoError("UNSUPPORTED_VERSION", "unsupported blob version: " + version);
  }

  const iv = blob.subarray(IV_OFFSET, IV_OFFSET + IV_LEN);
  const tag = blob.subarray(TAG_OFFSET, TAG_OFFSET + TAG_LEN);
  const ciphertext = blob.subarray(HEADER_LEN);

  const key = keyForVersion(version);
  const aad = buildAad(opts.invoiceId, opts.attachmentId);

  const decipher = crypto.createDecipheriv("aes-256-gcm", key, iv, { authTagLength: TAG_LEN });
  decipher.setAAD(aad);
  decipher.setAuthTag(tag);

  try {
    return Buffer.concat([decipher.update(ciphertext), decipher.final()]);
  } catch (e) {
    // GCM tag mismatch: tampered ciphertext/tag/IV, wrong key, or an AAD that
    // does not match this invoice + attachment pair. Never distinguish which.
    throw new AttachmentCryptoError(
      "AUTH_FAILED",
      "attachment failed authentication - wrong key, wrong invoice/attachment, or tampered data"
    );
  }
}

/* -------------------------------- helpers -------------------------------- */

// Cheap structural check used as a hard guard at the upload boundary: a raw
// PDF (which starts with "%PDF-") can never satisfy this.
function isSealedBlob(buf) {
  return Buffer.isBuffer(buf) &&
    buf.length >= HEADER_LEN &&
    buf.subarray(0, MAGIC.length).equals(MAGIC) &&
    SUPPORTED_VERSIONS.indexOf(buf[VERSION_OFFSET]) !== -1;
}

function describeBlob(buf) {
  if (!isSealedBlob(buf)) return null;
  return {
    version: buf[VERSION_OFFSET],
    headerLength: HEADER_LEN,
    ciphertextLength: buf.length - HEADER_LEN,
    totalLength: buf.length
  };
}

module.exports = {
  AttachmentCryptoError,
  MAGIC,
  HEADER_LEN,
  IV_LEN,
  TAG_LEN,
  KEY_LEN,
  SUPPORTED_VERSIONS,
  newAttachmentId,
  sealAttachment,
  openAttachment,
  isSealedBlob,
  describeBlob,
  currentVersion
};
